"""Initial migration

Revision ID: 559301f88481
Revises: 
Create Date: 2025-07-22 13:06:56.928091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559301f88481'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit')
    # ### end Alembic commands ###
